export function mountPromptTransfer(T){
  const $=id=>document.getElementById(id),panel=document.createElement('details');
  panel.innerHTML='<summary>비슷한 이미지에 프롬프트 재사용</summary><label>저장 이름 (영문/숫자/_/-) <input id="promptPresetName" value="recipe_1"></label><button id="savePromptPreset">현재 점·box를 preset으로 저장</button><label>저장한 preset <select id="promptPresetSelect"></select></label><label>좌표 변환 <select id="promptTransferMethod"><option value="normalized">영상 크기 비율 (정합 안 함)</option><option value="ecc">ECC 영상 정합 (작은 회전·이동)</option><option value="ecc_masked">양쪽 제외 ECC · 중앙 50% (실험적)</option></select></label><button id="previewPromptTransfer">현재 이미지에 점·box 미리보기</button><p id="promptTransferInfo">다른 이미지로 이동 후 적용하세요. 기존 준비 점·box는 교체됩니다. SAM은 별도로 실행하며 영상·마스크는 변형하지 않습니다.</p>';
  $('promptCount').closest('details').after(panel);
  function render(){const old=$('promptPresetSelect').value;$('promptPresetSelect').innerHTML=Object.values(T.state.prompt_presets||{}).map(p=>`<option value="${T.escape(p.id)}">${T.escape(p.id)} · ${T.escape(T.state.images[p.source_image]?.name||'기준 영상 삭제됨')}</option>`).join('');if(T.state.prompt_presets?.[old])$('promptPresetSelect').value=old}
  $('savePromptPreset').onclick=()=>T.task(async()=>{const key=$('promptPresetName').value.trim();if(T.state.prompt_presets?.[key]&&!await T.confirm('같은 이름의 preset을 현재 점·box로 바꿀까요? Undo로 복구할 수 있습니다.'))return;await T.api('workflow/prompt-presets/save',{image_id:T.current,preset_id:key,draft:T.promptDraft()});await T.refresh();$('promptPresetSelect').value=key});
  $('previewPromptTransfer').onclick=()=>T.task(async()=>{const r=await T.api('workflow/prompt-presets/preview',{image_id:T.current,preset_id:$('promptPresetSelect').value,method:$('promptTransferMethod').value});T.setPromptDraft(r.draft);$('promptTransferInfo').textContent=`${r.method} ${r.ecc_score==null?'':('ECC '+r.ecc_score.toFixed(3))} · ${r.warnings.join(' ')}`;T.say('점·box만 준비했습니다. 위치 확인 후 SAM 실행을 누르세요.')});
  window.addEventListener('tem:refreshed',render);return {render};
}
