export function mountROIAuto(T){
  const $=id=>document.getElementById(id),panel=document.createElement('details');let proposal=null,loaded=false;
  panel.innerHTML='<summary>독립 ROI 자동 후보 (수동 객체와 다른 모드)</summary><p>부모 없는 ROI에서 Grid/feature로 여러 후보를 생성합니다. 기존 수동 후보 1/2/3은 한 객체의 대안입니다. 아래 자동 후보는 필터별 독립 결과입니다. 전처리는 SAM 화면에서 저장한 값을 사용합니다.</p><label>방식 <select id="roiAutoSource"><option value="grid">Grid</option><option value="features">ML/에지</option><option value="grid_features">Grid+ML/에지</option></select></label><label>Grid 한 변 <input id="roiAutoGrid" type="number" min="2" max="16" value="4"></label><label>IoU <input id="roiAutoPred" type="number" min="0" max="1" step=".01" value=".90"></label><label>Stability <input id="roiAutoStability" type="number" min="0" max="1" step=".01" value=".92"></label><label>NMS <input id="roiAutoNms" type="number" min="0" max="1" step=".01" value=".8"></label><p>ML 방법/노이즈 제거/점 수는 SAM 페이지 설정을 사용합니다. 수동점은 이 자동 모드에 포함되지 않습니다.</p><button id="roiAutoRun">현재 ROI로 자동 후보 제안</button><p id="roiAutoInfo"></p><img id="roiAutoPreview" class="result-preview" alt="독립 ROI 자동 후보"><div id="roiAutoRows"></div><button id="roiAutoAccept" disabled>선택 후보 확인 후 저장</button>';
  $('roiRun').before(panel);
  function payload(){const e=T.roiEditor;if(e.parent!=null)throw Error('자동 후보는 부모 없는 독립 ROI에서 사용하세요.');return {image_id:e.imageId,roi:e.roi,prompt_source:$('roiAutoSource').value,grid:+$('roiAutoGrid').value,pred_iou:+$('roiAutoPred').value,stability:+$('roiAutoStability').value,nms:+$('roiAutoNms').value,feature_settings:T.featurePromptConfig()}}
  function gate(){$('roiAutoAccept').disabled=T.busy||T.roiEditor.busy||!proposal||!loaded}
  $('roiAutoPreview').onload=()=>{loaded=$('roiAutoPreview').naturalWidth>0;gate()};$('roiAutoPreview').onerror=()=>{loaded=false;gate()};
  $('roiAutoRun').onclick=()=>T.task(async()=>{if(T.roiEditor.busy)throw Error('수동 추론 완료 후 실행하세요.');proposal=null;loaded=false;gate();const p=payload(),signature=JSON.stringify(p),r=await T.api('sam/roi-auto/preview',p);proposal={...r,signature};$('roiAutoInfo').textContent=`${r.count}개 후보 / ${r.prompt_count}점 · 미저장 · ${r.note}`;$('roiAutoRows').innerHTML=r.candidates.map(c=>`<label><input type="checkbox" data-roi-auto-index="${c.index}" checked>후보 ${c.index+1} · ${c.area}px <button type="button" data-roi-view="${c.index}">보기</button></label>`).join('');$('roiAutoPreview').src=`/api/roi-auto/${r.token}.png`;gate()});
  $('roiAutoRows').onclick=e=>{const button=e.target.closest('[data-roi-view]');if(button&&proposal){loaded=false;gate();$('roiAutoPreview').src=`/api/roi-auto/${proposal.token}.png?index=${button.dataset.roiView}`}};
  $('roiAutoAccept').onclick=()=>T.task(async()=>{if(!proposal||!loaded)throw Error('미리보기를 먼저 확인하세요.');if(proposal.signature!==JSON.stringify(payload()))throw Error('입력이 바뀌었습니다. 다시 제안하세요.');const indices=[...$('roiAutoRows').querySelectorAll('input:checked')].map(x=>+x.dataset.roiAutoIndex);if(!await T.confirm(`${indices.length}개 ROI 후보를 저장할까요? 기존 후보는 보존되며 새 결과는 미검수 상태입니다.`))return;const r=await T.api('sam/roi-auto/accept',{token:proposal.token,indices,image_id:T.current});proposal=null;loaded=false;await T.refresh();$('roiAutoInfo').textContent=`${r.count}개 후보 저장됨. 레이어 배정은 별도입니다.`;gate()});
  window.addEventListener('tem:idle',gate);$('roiClose').addEventListener('click',()=>{proposal=null;loaded=false;gate()});
}
