/* v2 review controls. Requests retain image/candidate identities while busy. */
let boundaryDraft=null,boundaryOwner=null,profileSelection=null,localEndpoint=null,pins=[],overrides=[],imageSelection=new Set(),selectionAnchor=null,dragSelecting=false;
const originalRefresh=refresh,originalRedraw=redraw,originalGallery=renderGallery;
refresh=async function(){await originalRefresh();if(boundaryOwner!==current){boundaryDraft=null;profileSelection=null;pins=[];overrides=[];boundaryOwner=current}const list=(state.candidates[current]||[]).filter(c=>!c.deleted);for(const [id,items] of [['neighbor',list.filter(c=>c.active!==false&&c.layer_id!=null)],['reference',list.filter(c=>c.reviewed)]]){const previous=$(id).value;$(id).innerHTML=(id==='neighbor'?'<option value="">명시적 배경</option>':'')+items.map(c=>`<option value="${c.id}">#${c.id} ${escapeHtml(candidateName(c))} (L${c.layer_id??'—'})</option>`).join('');if(items.some(c=>String(c.id)===previous))$(id).value=previous}loadFilterControls();$('undo').textContent=`Undo (${state.undo_count||0})`;$('redo').textContent=`Redo (${state.redo_count||0})`;updateConstraints();redraw()};
function updateConstraints(){$('constraintInfo').textContent=`고정점 ${pins.length}개 · 부분 설정 ${overrides.length}개 (미리보기 재실행 필요)`}
for(const action of ['undo','redo'])$(action).onclick=()=>task(async()=>{await api('v2/'+action,{});boundaryDraft=null;await refresh()});
$('loadModel').onclick=()=>task(async()=>{await api('model/load',{checkpoint:$('checkpoint').value,variant:$('variant').value,device:$('device').value,decoder_path:$('decoder').value||null,adaptation_path:$('adaptation').value||null});await refresh()});
function loadFilterControls(){const c=state.preprocessing?.[current]?.[$('filterBranch').value+'_filter']||{};$('filterEnabled').checked=!!c.enabled;$('filterMethod').value=c.method||'gaussian';$('filterSigma').value=c.sigma??1;$('filterRange').value=c.range_sigma??.08;$('filterContrast').value=c.contrast??1;$('filterMedian').value=c.median_size??3;$('filterNlm').value=c.nlm_h??10}
$('filterBranch').onchange=loadFilterControls;
$('saveFilter').onclick=()=>task(async()=>{await api('v2/filters',{image_id:current,branch:$('filterBranch').value,config:{enabled:$('filterEnabled').checked,method:$('filterMethod').value,sigma:+$('filterSigma').value,range_sigma:+$('filterRange').value,contrast:+$('filterContrast').value,median_size:+$('filterMedian').value,nlm_h:+$('filterNlm').value}});await refresh();say('현재 이미지 전처리 저장됨')});
$('previewFilter').onclick=()=>task(async()=>{const id=current;const im=await new Promise((resolve,reject)=>{let img=new Image();img.onload=()=>resolve(img);img.onerror=()=>reject(Error('미리보기 실패'));img.src=`/api/v2/filter/${id}/${$('filterBranch').value}.png?${Date.now()}`});if(current===id){base=im;redraw()}});
$('originalFilter').onclick=()=>task(async()=>{await loadImage();redraw()});
$('editSAM').onclick=()=>task(async()=>{if(!selected())throw Error('수정할 후보를 선택하세요');await ensureAnalysisRegions();let x=await api('sam/prompt',{image_id:current,parent:selected(),mode:'edit',points,box});await refresh();$('candidateSelect').value=x.id;await loadMask();say('수정 제안입니다. 부모 교체로 확정하거나 취소하세요')});
$('cancelCandidate').onclick=()=>task(async()=>{const c=(state.candidates[current]||[]).find(c=>c.id===selected());if(!c||c.layer_id!==null)throw Error('레이어에 지정되지 않은 미확정 후보만 취소할 수 있습니다');await api('candidates/'+current+'/'+c.id,null,'DELETE');await refresh()});
$('assign').onclick=()=>task(async()=>{const c=(state.candidates[current]||[]).find(c=>c.id===selected());if(!c)throw Error('후보를 선택하세요');const mode=c.parent?$('assignMode').value:'add';await api('layers/assign',{image_id:current,candidate_id:c.id,layer_id:+$('layerSelect').value,instance_id:$('instance').value||null,reviewed:false,mode,replace_id:c.parent});await refresh();$('candidateSelect').value=c.id;await loadMask();say('레이어에 배정했습니다. 마스크 검수 확정은 별도입니다.')});
$('lockLayer').onclick=()=>task(async()=>{let layer=state.layers.find(l=>l.id===+$('layerSelect').value);if(!layer)throw Error('레이어를 선택하세요');await api('v2/lock',{layer_id:layer.id,locked:!layer.locked});await refresh();say(layer.locked?'레이어 잠금 해제':'레이어 잠금')});
$('ocrBatch').onclick=()=>task(async()=>{const r=await api('v2/ocr-batch',{image_ids:Object.keys(state.images),ocr_dir:$('ocrDir').value,fallback_length:+$('scaleLength').value||null,unit:$('scaleUnit').value});await refresh();restoreScale();say(`이미지별 OCR 완료: 오류 ${Object.values(r).filter(x=>x.error).length}개. 제안값을 검수하세요.`)});
renderGallery=function(){originalGallery();for(const id of imageSelection)if(!state.images[id])imageSelection.delete(id);for(const el of document.querySelectorAll('#imageGallery [data-image]')){el.classList.toggle('multi-selected',imageSelection.has(el.dataset.image))}$('selectedCount').textContent=`${imageSelection.size}개 선택`};
function selectImageTile(id,event){const ids=Object.keys(state.images);if(event.shiftKey&&selectionAnchor){let a=ids.indexOf(selectionAnchor),b=ids.indexOf(id);if(!event.ctrlKey&&!event.metaKey)imageSelection.clear();for(let i=Math.min(a,b);i<=Math.max(a,b);i++)imageSelection.add(ids[i])}else{if(!event.ctrlKey&&!event.metaKey)imageSelection.clear();if((event.ctrlKey||event.metaKey)&&imageSelection.has(id))imageSelection.delete(id);else imageSelection.add(id);selectionAnchor=id}renderGallery()}
$('imageGallery').onclick=e=>{if(uiBusy)return;const tile=e.target.closest('[data-image]');if(!tile)return;if($('multiSelect').checked||e.ctrlKey||e.metaKey||e.shiftKey){if(!dragSelecting)selectImageTile(tile.dataset.image,e)}else switchImage(tile.dataset.image)};
$('imageGallery').addEventListener('pointerdown',e=>{if(uiBusy||!$('multiSelect').checked||e.button!==0)return;const tile=e.target.closest('[data-image]');if(!tile)return;selectImageTile(tile.dataset.image,e);dragSelecting=true;e.preventDefault()});
$('imageGallery').addEventListener('pointerover',e=>{if(!dragSelecting||!e.buttons)return;const tile=e.target.closest('[data-image]');if(tile){imageSelection.add(tile.dataset.image);tile.classList.add('multi-selected');$('selectedCount').textContent=`${imageSelection.size}개 선택`}});
document.addEventListener('pointerup',()=>{if(dragSelecting)setTimeout(()=>{dragSelecting=false},0)});
$('deleteSelected').onclick=()=>task(async()=>{const ids=[...imageSelection];if(!ids.length)throw Error('삭제할 이미지를 선택하세요');if(!await confirmAction(`${ids.length}개 이미지를 삭제할까요? 삭제 파일은 프로젝트 trash에 보존됩니다.`))return;const r=await api('v2/delete',{image_ids:ids});for(const id of r.deleted){delete imageDrafts[id];imageSelection.delete(id)}await refresh();if(Object.keys(r.failed).length)throw Error('삭제 실패: '+JSON.stringify(r.failed));say(`${r.count}개 삭제됨`)});
function boundarySettings(){return {inside:+$('inside').value,outside:+$('outside').value,polarity:$('polarity').value,smooth:+$('smooth').value,distance:+$('distance').value,jump:+$('jump').value,weak:.12}}
$('boundaryPreview').onclick=()=>task(async()=>{boundaryDraft=await api('v2/boundary/preview',{image_id:current,candidate_id:selected(),neighbor_id:+$('neighbor').value||null,settings:boundarySettings(),pins,overrides});boundaryOwner=current;await showBinary(`/api/v2/boundary/${boundaryDraft.token}.png`,'#35e580');$('boundaryInfo').textContent=`변경 ${boundaryDraft.changed_pixels} px. `+boundaryDraft.loops.flatMap(l=>l.quality.flags).join(' / ');redraw()});
$('boundaryApply').onclick=()=>task(async()=>{if(!boundaryDraft)throw Error('먼저 미리보기를 실행하세요');const r=await api('v2/boundary/apply',{token:boundaryDraft.token});boundaryDraft=null;await refresh();if(r.created[0]){$('candidateSelect').value=r.created[0].id;await loadMask()}say(`공유 경계 적용: ${r.changed_pixels} px`)});
$('boundaryCancel').onclick=()=>task(async()=>{if(boundaryDraft)await api('v2/boundary/cancel',{token:boundaryDraft.token});boundaryDraft=null;await loadMask();redraw()});
redraw=function(){originalRedraw();if(!boundaryDraft||current!==boundaryOwner||!$('boundaryLines').checked)return;ctx.save();ctx.translate(panX,panY);ctx.scale(fit*zoom,fit*zoom);ctx.lineWidth=1.5/(fit*zoom);for(const l of boundaryDraft.loops)for(const [key,color] of [['initial','#ffffff'],['peak','#ff9b3d'],['refined','#3ee8ed']]){const ps=l[key];if(!ps?.length)continue;ctx.strokeStyle=color;ctx.beginPath();ctx.moveTo(...ps[0]);for(const p of ps.slice(1))ctx.lineTo(...p);ctx.closePath();ctx.stroke()}ctx.restore()};
$('boundaryLines').onchange=redraw;$('profileTool').onclick=()=>{$('tool').value='profile'};
canvas.addEventListener('pointerdown',e=>{if(uiBusy||$('tool').value!=='profile'||!boundaryDraft)return;const p=coord(e);let nearest=null;boundaryDraft.loops.forEach((loop,li)=>loop.initial.forEach((q,i)=>{let d=Math.hypot(p[0]-q[0],p[1]-q[1]);if(!nearest||d<nearest.d)nearest={loop:li,index:i,d}}));if(nearest)task(async()=>{const r=await api(`v2/boundary/${boundaryDraft.token}/profile?loop=${nearest.loop}&index=${nearest.index}`,null,'GET');profileSelection={...nearest,...r};plotProfile(r);$('profileInfo').textContent=`경계 ${nearest.loop} / 점 ${nearest.index}: 이동 ${r.chosen.toFixed(2)} px ${r.uncertain?'· 검수 필요':''}`})});
function plotProfile(r){let c=$('profilePlot'),x=c.getContext('2d'),w=c.width,h=c.height;x.fillStyle='#17212b';x.fillRect(0,0,w,h);const lo=r.offset[0],hi=r.offset.at(-1),max=Math.max(...r.gradient,1e-8),px=v=>25+(v-lo)/(hi-lo)*(w-35),py=v=>h-25-v/max*(h-40);x.strokeStyle='#ffd057';x.beginPath();r.gradient.forEach((v,i)=>i?x.lineTo(px(r.offset[i]),py(v)):x.moveTo(px(r.offset[i]),py(v)));x.stroke();x.strokeStyle='#43eeee';x.beginPath();x.moveTo(px(r.chosen),10);x.lineTo(px(r.chosen),h-25);x.stroke();x.fillStyle='white';x.font='12px sans-serif';x.fillText(`${lo} px`,5,h-5);x.fillText(`${hi} px`,w-48,h-5);x.fillText('정규화 법선 gradient',30,14)}
$('addPin').onclick=()=>{if(!profileSelection)return say('프로파일 지점을 먼저 선택하세요');const p=profileSelection;const d=+$('pinOffset').value;pins.push({loop:p.loop,point:p.point.map((v,i)=>v+d*p.normal[i])});updateConstraints()};
$('localStart').onclick=()=>{if(!profileSelection)return say('프로파일 지점을 선택하세요');localEndpoint={loop:profileSelection.loop,point:profileSelection.point};say('부분 구간 시작점 저장')};
$('localEnd').onclick=()=>{if(!localEndpoint||!profileSelection||localEndpoint.loop!==profileSelection.loop)return say('같은 경계에서 시작점과 끝점을 선택하세요');overrides.push({loop:profileSelection.loop,endpoints:[localEndpoint.point,profileSelection.point],inside:+$('inside').value,outside:+$('outside').value,polarity:$('polarity').value});localEndpoint=null;updateConstraints()};
$('clearConstraints').onclick=()=>{pins=[];overrides=[];localEndpoint=null;updateConstraints()};
$('annotate').onclick=()=>task(async()=>{if(!strokes.length)throw Error('브러시 추가 도구로 영역을 그리세요');await api('v2/annotations',{image_id:current,kind:$('annotationKind').value,strokes});strokes=[];await refresh()});
$('showLabels').onclick=()=>task(async()=>{const id=current;let im=await new Promise((resolve,reject)=>{const x=new Image();x.onload=()=>resolve(x);x.onerror=()=>reject(Error('GT 표시 실패'));x.src=`/api/v2/labels/${id}.png?${Date.now()}`});if(current===id){coverage=im;tint=null;showCov=true;redraw()}});
function downloadBlob(blob,name){const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
$('exportGT').onclick=()=>task(async()=>{if(!current)throw Error('이미지를 선택하세요');const r=await api(`v2/export/${current}.zip`,null,'GET');downloadBlob(await r.blob(),`TEM_GT_${current}.zip`)});
async function evaluate(csv=false){const r=await api('v2/evaluate',{image_id:current,candidate_id:selected(),reference_id:+$('reference').value,tolerance:+$('tolerance').value,csv});if(csv)downloadBlob(await r.blob(),'evaluation.csv');else $('evaluation').textContent=JSON.stringify(r,null,2)}
$('evaluate').onclick=()=>task(()=>evaluate());$('evaluateCSV').onclick=()=>task(()=>evaluate(true));
// The modal's inference must also freeze navigation and image deletion.
const originalROIRun=roiEditor.run.bind(roiEditor);roiEditor.run=async()=>{await task(originalROIRun);roiEditor.updateButtons()};

function initializeV2(){return task(()=>refresh())}

const originalLoadMask=loadMask;let constraintCandidate=null;
loadMask=async function(changeMode=true){if(constraintCandidate!==selected()){boundaryDraft=null;profileSelection=null;pins=[];overrides=[];constraintCandidate=selected();updateConstraints()}return originalLoadMask(changeMode)};
